### ISSUE TITLE
Roblox API

### ISSUE THREAD

**Issue by sbhadr** [ext0/RobloxSharp#1]
I saw that you created a Roblox API library in C#. I want to get in touch with you. 

I couldn't express much of what I wanted to say in this short body. Please have a look at [this](https://forum.roblox.com/Forum/ShowPost.aspx?PostID=221414751) for more information.

The link is a roblox forum link. If you don't like forums, I'd be happy to explain further here.
Hope to hear your response soon! :)

**Comment by ext0** [comment]
So you're looking to create or find a wrapper? My RobloxSharp
implementation did exactly that, but I'm sure it no longer works due to API
changes. As for creating a wrapper, I would recommend utilizing web
debugger tools like Fiddler to intercept and analyze the calls ROBLOX uses.

**Comment by sbhadr** [comment]
Im looking to align your wrapper for user's that want to use it in the future. Intrestingly enough, I created a Roblox API wrapper in Python recently due to a lack of user-made Roblox Libraries/Wrappers. 

I was wondering if you'd like to help us with the purpose of making user-made Roblox Libraries/Wrappers publicly available for third-party uses. I recently created a Discord server( https://discord.gg/EDXNdAT ). Another developer(who created a roblox library via node.js) has decided to help me with this effort. 

The discord server serves as a place where developers can properly interact with their user-base or promote their respective repos.

**Comment by sbhadr** [comment]
I await a response.

**Comment by ext0** [comment]
I unfortunately don't have the time to continue working on any kind of wrapper, but I can answer any questions regarding my wrapper.

**Comment by sbhadr** [comment]
Does your wrapper provide basic functionality?

**Comment by ext0** [comment]
Yes. The uses are documented in the README.md

**Comment by sbhadr** [comment]
Could you join our discord server? Furthermore, we can add your repo to our list. 

Link: https://discord.gg/EDXNdAT
